services:
        nginx:
                image: nginx:inception
                container_name: nginx
                build: requirements/nginx
                env_file: .env
                depends_on:
                        - wordpress
                        - adminer
                ports:
                        - "443:443"
                volumes:
                        - ../logs/nginx:/var/log/nginx
                        - wordpress_vol:/var/www/html
                networks:
                        - inception-net
                restart: on-failure
        wordpress:
                image: wordpress:inception
                container_name: wordpress
                build: requirements/wordpress
                env_file: .env
                expose:
                        - "9000"
                depends_on:
                        - mariadb
                volumes:
                        - ../logs/wordpress:/var/log
                        - wordpress_vol:/var/www/html
                networks:
                        - inception-net
                restart: on-failure
        mariadb:
                image: mariadb:inception
                container_name: mariadb
                build: requirements/mariadb
                env_file: .env
                expose:
                        - "3306"
                volumes:
                        - ../logs/mariadb:/var/log/mysql
                        - mariadb_vol:/var/lib/mysql
                networks:
                        - inception-net
                restart: on-failure
        redis:
                image: redis:inception
                container_name: redis
                build: requirements/bonus/redis
                env_file: .env
                expose:
                        - "6379"
                networks:
                        - inception-net
                restart: on-failure
        adminer:
                image: adminer:inception
                container_name: adminer
                build: requirements/bonus/adminer
                env_file: .env
                depends_on:
                        - mariadb
                expose:
                        - "8080"
                networks:
                        - inception-net
                restart: on-failure
        ftp:
                image: ftp:inception
                container_name: ftp
                build: requirements/bonus/ftp
                env_file: .env
                ports:
                        - "40000-40005:40000-40005"
                        - "20:20"
                        - "21:21"
                depends_on:
                        - wordpress
                volumes:
                        - wordpress_vol:/home/${FTP_USER}/ftp
                networks:
                        - inception-net
                restart: on-failure
        mariabackup:
                image: mariabackup:inception
                container_name: mariabackup
                build: requirements/bonus/mariabackup
                env_file: .env
                environment:
                        CONTINENT: ${CONTINENT}
                        STATE: ${SSL_STATE}
                depends_on:
                        - mariadb
                volumes:
                        - mariadb_vol:/var/lib/mysql
                        - ../backups:/backups
                networks:
                        - inception-net
                restart: on-failure

volumes:
        wordpress_vol:
                driver: local
                driver_opts:
                        type: 'none'
                        o: 'bind'
                        device: '${HOME}/data/wordpress'
        mariadb_vol:
                driver: local
                driver_opts:
                        type: 'none'
                        o: 'bind'
                        device: '${HOME}/data/mariadb'

networks:
        inception-net:
                driver: bridge
