services:
        nginx:
                image: nginx:inception
                container_name: nginx
                build: ./requirements/nginx
                env_file: .env
                depends_on:
                        - wordpress
                ports:
                        - "443:443"
                volumes:
                        - ../logs/nginx:/var/log/nginx
                        - wordpress_vol:/var/www/html
                networks:
                        - inception-net
                restart: on-failure
        wordpress:
                image: wordpress:inception
                container_name: wordpress
                build: ./requirements/wordpress
                env_file: .env
                expose:
                        - "9000"
                depends_on:
                        - mariadb
                volumes:
                        - ../logs/wordpress:/var/log
                        - wordpress_vol:/var/www/html
                networks:
                        - inception-net
                restart: on-failure
        mariadb:
                image: mariadb:inception
                container_name: mariadb
                build: ./requirements/mariadb
                env_file: .env
                expose:
                        - "3306"
                volumes:
                        - ../logs/mariadb:/var/log/mysql
                        - mariadb_vol:/var/lib/mysql
                networks:
                        - inception-net
                restart: on-failure
        redis:
                image: redis:inception
                container_name: redis
                build: ./requirements/bonus/redis
                env_file: .env
                ports:
                        - "6379:6379"
                networks:
                        - inception-net
                restart: on-failure

volumes:
        wordpress_vol:
                driver: local
                driver_opts:
                        type: 'none'
                        o: 'bind'
                        device: '${HOME}/data/wordpress'
        mariadb_vol:
                driver: local
                driver_opts:
                        type: 'none'
                        o: 'bind'
                        device: '${HOME}/data/mariadb'

networks:
        inception-net:
                driver: bridge
