services:
        nginx:
                image: nginx:1.28.0
                container_name: nginx
                build: ./requirements/nginx
                ports:
                        - "80:80"
                volumes:
                        - ../logs/nginx:/var/log/nginx
