# Mapper un volume
services:
        orange:
                image: celtak/ubuntu-ping-ip
                container_name: celtak_ubuntu
                stdin_open: true
                tty: true
                volumes:
                       - ./data:/data
