FROM celtak/ubuntu-ping-ip
RUN apt update
RUN apt install -y nodejs

#FROM ubuntu:22.04
#RUN apt update
#RUN apt install -y git
#RUN apt install -y vim
#RUN apt install -y make
#RUN apt install -y g++
#RUN apt install -y python3
#RUN apt install -y valgrind
#ADD /Webserv /Webserv
#LABEL description="Webserv sur Linux"
#LABEL version="1.1"
