services:
        nginx:
                image: nginx:latest
                container_name: nginx
                build: ./srcs/nginx
                ports:
                        - "80:80"
                volumes:
                        - ./logs/nginx:/var/log/nginx
